import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Toogle from "../components/Toogle";
import Navbar from "../components/Navbar/Navbar";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <div className={styles.box}>
          <Toogle />
        </div>
      </main>
    </div>
  );
}
